### ISSUE TITLE
Test and fix boatd running under py35

### ISSUE THREAD

**Issue by kragniz** [boatd/boatd#13]
Fedora depending on enum34 is messing up virtualenv builds locally, so this might have to wait until I'm using a more nixy OS:

```
py35 create: /home/louis/git/boatd/.tox/py35
ERROR: invocation failed (exit code 1), logfile: /home/louis/git/boatd/.tox/py35/log/py35-0.log
ERROR: actionid: py35
msg: getenv
cmdargs: ['/usr/bin/python', '-m', 'virtualenv', '--python', '/bin/python3.5', 'py35']
env: {some stuff}

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/enum/__init__.py", line 371, in __getattr__
    return cls._member_map_[name]
KeyError: '_convert'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 23, in <module>
    import subprocess
  File "/usr/lib64/python3.5/subprocess.py", line 364, in <module>
    import signal
  File "/usr/lib64/python3.5/signal.py", line 8, in <module>
    _IntEnum._convert(
  File "/usr/lib/python2.7/site-packages/enum/__init__.py", line 373, in __getattr__
    raise AttributeError(name)
AttributeError: _convert
Running virtualenv with interpreter /bin/python3.5

ERROR: InvocationError: /usr/bin/python -m virtualenv --python /bin/python3.5 py35 (see /home/louis/git/boatd/.tox/py35/log/py35-0.log)
____________________________________________________ summary ____________________________________________________
  py27: commands succeeded
  py34: commands succeeded
ERROR:   py35: InvocationError: /usr/bin/python -m virtualenv --python /bin/python3.5 py35 (see /home/louis/git/boatd/.tox/py35/log/py35-0.log)
```

**Comment by blbradley** [comment]
I'm getting this same error in one of my own projects. Running in Ubuntu. I think it is an error with tox.

**Comment by blbradley** [comment]
`virtualenv` package was out of date.

**Comment by kragniz** [comment]
Thanks, which venv version fixed it?

**Comment by blbradley** [comment]
14.0.x

**Comment by kragniz** [comment]
Not an issue anymore on any of the platforms I tested on.
